apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-sensors
  labels:
    app.kubernetes.io/part-of: spring-sensors
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: true
spec:
  source:
    git:
      url: https://github.com/pedersenju/spring-sensors-rabbit.git
      ref:
        branch: master
  serviceClaims:
    - name: rmq
      ref:
        apiVersion: rabbitmq.com/v1beta1
        kind: RabbitmqCluster
        name: rmq-1

